export const initialTeams = [
  // Anfitriones
  {
    id: "can",
    name: "Canadá",
    flagCode: "ca",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },
  {
    id: "usa",
    name: "Estados Unidos",
    flagCode: "us",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },
  {
    id: "mex",
    name: "México",
    flagCode: "mx",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },

  // UEFA (Europa)
  {
    id: "eng",
    name: "Inglaterra",
    flagCode: "gb-eng",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "fra",
    name: "Francia",
    flagCode: "fr",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ger",
    name: "Alemania",
    flagCode: "de",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "esp",
    name: "España",
    flagCode: "es",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "bel",
    name: "Bélgica",
    flagCode: "be",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "cro",
    name: "Croacia",
    flagCode: "hr",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "den",
    name: "Dinamarca",
    flagCode: "dk",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ned",
    name: "Países Bajos",
    flagCode: "nl",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "pol",
    name: "Polonia",
    flagCode: "pl",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "por",
    name: "Portugal",
    flagCode: "pt",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "srb",
    name: "Serbia",
    flagCode: "rs",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "sui",
    name: "Suiza",
    flagCode: "ch",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "tur",
    name: "Turquía",
    flagCode: "tr",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ukr",
    name: "Ucrania",
    flagCode: "ua",
    description: "Clasificado por UEFA (Europa).",
  },

  // CONMEBOL (Sudamérica)
  {
    id: "arg",
    name: "Argentina",
    flagCode: "ar",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "bra",
    name: "Brasil",
    flagCode: "br",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "ecu",
    name: "Ecuador",
    flagCode: "ec",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "uru",
    name: "Uruguay",
    flagCode: "uy",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "ven",
    name: "Venezuela",
    flagCode: "ve",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "par",
    name: "Paraguay",
    flagCode: "py",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "chi",
    name: "Chile",
    flagCode: "cl",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "col",
    name: "Colombia",
    flagCode: "co",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "per",
    name: "Perú",
    flagCode: "pe",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "bol",
    name: "Bolivia",
    flagCode: "bo",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },

  // AFC (Asia)
  {
    id: "jpn",
    name: "Japón",
    flagCode: "jp",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kor",
    name: "Corea del Sur",
    flagCode: "kr",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "irn",
    name: "Irán",
    flagCode: "ir",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ksa",
    name: "Arabia Saudita",
    flagCode: "sa",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "aus",
    name: "Australia",
    flagCode: "au",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "qat",
    name: "Catar",
    flagCode: "qa",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "oma",
    name: "Omán",
    flagCode: "om",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "irq",
    name: "Irak",
    flagCode: "iq",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "uzb",
    name: "Uzbekistán",
    flagCode: "uz",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kgz",
    name: "Kirguistán",
    flagCode: "kg",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "vie",
    name: "Vietnam",
    flagCode: "vn",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tha",
    name: "Tailandia",
    flagCode: "th",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "idn",
    name: "Indonesia",
    flagCode: "id",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "phi",
    name: "Filipinas",
    flagCode: "ph",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mas",
    name: "Malasia",
    flagCode: "my",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "cam",
    name: "Camboya",
    flagCode: "kh",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "sgp",
    name: "Singapur",
    flagCode: "sg",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "bhr",
    name: "Bahréin",
    flagCode: "bh",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "yem",
    name: "Yemen",
    flagCode: "ye",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "jor",
    name: "Jordania",
    flagCode: "jo",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "lbn",
    name: "Líbano",
    flagCode: "lb",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ple",
    name: "Palestina",
    flagCode: "ps",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "syr",
    name: "Siria",
    flagCode: "sy",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "afg",
    name: "Afganistán",
    flagCode: "af",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ban",
    name: "Bangladés",
    flagCode: "bd",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "nep",
    name: "Nepal",
    flagCode: "np",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "bhu",
    name: "Bután",
    flagCode: "bt",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mdv",
    name: "Islas Maldivas",
    flagCode: "mv",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tls",
    name: "Timor Oriental",
    flagCode: "tl",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mng",
    name: "Mongolia",
    flagCode: "mn",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tjk",
    name: "Tayikistán",
    flagCode: "tj",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tkm",
    name: "Turkmenistán",
    flagCode: "tm",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kaz",
    name: "Kazajistán",
    flagCode: "kz",
    description: "Participante de las clasificatorias de Asia.",
  },

  // OFC (Oceanía)
  {
    id: "kir",
    name: "Kiribati",
    flagCode: "ki",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "sam",
    name: "Samoa",
    flagCode: "ws",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tga",
    name: "Tonga",
    flagCode: "to",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "fij",
    name: "Fiyi",
    flagCode: "fj",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "van",
    name: "Vanuatu",
    flagCode: "vu",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "sol",
    name: "Islas Salomón",
    flagCode: "sb",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "png",
    name: "Papúa Nueva Guinea",
    flagCode: "pg",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "nru",
    name: "Nauru",
    flagCode: "nr",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "plw",
    name: "Palau",
    flagCode: "pw",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "fsm",
    name: "Micronesia",
    flagCode: "fm",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "mhl",
    name: "Islas Marshall",
    flagCode: "mh",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tuv",
    name: "Tuvalu",
    flagCode: "tv",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "niu",
    name: "Niue",
    flagCode: "nu",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "cok",
    name: "Cook Islands",
    flagCode: "ck",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tkl",
    name: "Tokelau",
    flagCode: "tk",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "wlf",
    name: "Wallis y Futuna",
    flagCode: "wf",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "pyf",
    name: "Polinesia Francesa",
    flagCode: "pf",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "ncl",
    name: "Nueva Caledonia",
    flagCode: "nc",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "asm",
    name: "Samoa Americana",
    flagCode: "as",
    description: "Participante de las clasificatorias de Oceanía.",
  },

  // CONCACAF (Norteamérica, Centroamérica y el Caribe)
  {
    id: "gum",
    name: "Guam",
    flagCode: "gu",
    description: "Participante de las clasificatorias de Oceanía / Asia.",
  },
  {
    id: "vir",
    name: "Islas Vírgenes Estadounidenses",
    flagCode: "vi",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "pur",
    name: "Puerto Rico",
    flagCode: "pr",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "hai",
    name: "Haití",
    flagCode: "ht",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "jam",
    name: "Jamaica",
    flagCode: "jm",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "tri",
    name: "Trinidad y Tobago",
    flagCode: "tt",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "guy",
    name: "Guyana",
    flagCode: "gy",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "sur",
    name: "Surinam",
    flagCode: "sr",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bar",
    name: "Barbados",
    flagCode: "bb",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "lca",
    name: "Santa Lucía",
    flagCode: "lc",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "vin",
    name: "San Vicente y las Granadinas",
    flagCode: "vc",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "grn",
    name: "Granada",
    flagCode: "gd",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "atg",
    name: "Antigua y Barbuda",
    flagCode: "ag",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "kna",
    name: "San Cristóbal y Nieves",
    flagCode: "kn",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "dma",
    name: "Dominica",
    flagCode: "dm",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "msr",
    name: "Montserrat",
    flagCode: "ms",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "aia",
    name: "Anguila",
    flagCode: "ai",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bmu",
    name: "Bermudas",
    flagCode: "bm",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "cym",
    name: "Islas Caimán",
    flagCode: "ky",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "tca",
    name: "Islas Turcas y Caicos",
    flagCode: "tc",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bhs",
    name: "Bahamas",
    flagCode: "bs",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "blz",
    name: "Belice",
    flagCode: "bz",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "slv",
    name: "El Salvador",
    flagCode: "sv",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "gua",
    name: "Guatemala",
    flagCode: "gt",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "hon",
    name: "Honduras",
    flagCode: "hn",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "nic",
    name: "Nicaragua",
    flagCode: "ni",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "crc",
    name: "Costa Rica",
    flagCode: "cr",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "pan",
    name: "Panamá",
    flagCode: "pa",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "dom",
    name: "República Dominicana",
    flagCode: "do",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "cub",
    name: "Cuba",
    flagCode: "cu",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
];
