export const initialTeams = [
  // Anfitriones
  {
    id: "can",
    name: "Canadá",
    flag: "🇨🇦",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },
  {
    id: "usa",
    name: "Estados Unidos",
    flag: "🇺🇸",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },
  {
    id: "mex",
    name: "México",
    flag: "🇲🇽",
    description: "País anfitrión del Mundial 2026. Clasificación automática.",
  },

  // UEFA (Europa)
  {
    id: "eng",
    name: "Inglaterra",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "fra",
    name: "Francia",
    flag: "🇫🇷",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ger",
    name: "Alemania",
    flag: "🇩🇪",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "esp",
    name: "España",
    flag: "🇪🇸",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "bel",
    name: "Bélgica",
    flag: "🇧🇪",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "cro",
    name: "Croacia",
    flag: "🇭🇷",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "den",
    name: "Dinamarca",
    flag: "🇩🇰",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ned",
    name: "Países Bajos",
    flag: "🇳🇱",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "pol",
    name: "Polonia",
    flag: "🇵🇱",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "por",
    name: "Portugal",
    flag: "🇵🇹",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "srb",
    name: "Serbia",
    flag: "🇷🇸",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "sui",
    name: "Suiza",
    flag: "🇨🇭",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "tur",
    name: "Turquía",
    flag: "🇹🇷",
    description: "Clasificado por UEFA (Europa).",
  },
  {
    id: "ukr",
    name: "Ucrania",
    flag: "🇺🇦",
    description: "Clasificado por UEFA (Europa).",
  },

  // CONMEBOL (Sudamérica)
  {
    id: "arg",
    name: "Argentina",
    flag: "🇦🇷",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "bra",
    name: "Brasil",
    flag: "🇧🇷",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "ecu",
    name: "Ecuador",
    flag: "🇪🇨",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "uru",
    name: "Uruguay",
    flag: "🇺🇾",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "ven",
    name: "Venezuela",
    flag: "🇻🇪",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "par",
    name: "Paraguay",
    flag: "🇵🇾",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "chi",
    name: "Chile",
    flag: "🇨🇱",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "col",
    name: "Colombia",
    flag: "🇨🇴",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "per",
    name: "Perú",
    flag: "🇵🇪",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },
  {
    id: "bol",
    name: "Bolivia",
    flag: "🇧🇴",
    description: "Clasificado por CONMEBOL (Sudamérica).",
  },

  // AFC (Asia)
  {
    id: "jpn",
    name: "Japón",
    flag: "🇯🇵",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kor",
    name: "Corea del Sur",
    flag: "🇰🇷",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "irn",
    name: "Irán",
    flag: "🇮🇷",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ksa",
    name: "Arabia Saudita",
    flag: "🇸🇦",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "aus",
    name: "Australia",
    flag: "🇦🇺",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "qat",
    name: "Catar",
    flag: "🇶🇦",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "oma",
    name: "Omán",
    flag: "🇴🇲",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "irq",
    name: "Irak",
    flag: "🇮🇶",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "uzb",
    name: "Uzbekistán",
    flag: "🇺🇿",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kgz",
    name: "Kirguistán",
    flag: "🇰🇬",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "vie",
    name: "Vietnam",
    flag: "🇻🇳",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tha",
    name: "Tailandia",
    flag: "🇹🇭",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "idn",
    name: "Indonesia",
    flag: "🇮🇩",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "phi",
    name: "Filipinas",
    flag: "🇵🇭",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mas",
    name: "Malasia",
    flag: "🇲🇾",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "cam",
    name: "Camboya",
    flag: "🇰🇭",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "sgp",
    name: "Singapur",
    flag: "🇸🇬",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "bhr",
    name: "Bahréin",
    flag: "🇧🇭",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "yem",
    name: "Yemen",
    flag: "🇾🇪",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "jor",
    name: "Jordania",
    flag: "🇯🇴",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "lbn",
    name: "Líbano",
    flag: "🇱🇧",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ple",
    name: "Palestina",
    flag: "🇵🇸",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "syr",
    name: "Siria",
    flag: "🇸🇾",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "afg",
    name: "Afganistán",
    flag: "🇦🇫",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "ban",
    name: "Bangladés",
    flag: "🇧🇩",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "nep",
    name: "Nepal",
    flag: "🇳🇵",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "bhu",
    name: "Bután",
    flag: "🇧🇹",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mdv",
    name: "Islas Maldivas",
    flag: "🇲🇻",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tls",
    name: "Timor Oriental",
    flag: "🇹🇱",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "mng",
    name: "Mongolia",
    flag: "🇲🇳",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tjk",
    name: "Tayikistán",
    flag: "🇹🇯",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "tkm",
    name: "Turkmenistán",
    flag: "🇹🇲",
    description: "Participante de las clasificatorias de Asia.",
  },
  {
    id: "kaz",
    name: "Kazajistán",
    flag: "🇰🇿",
    description: "Participante de las clasificatorias de Asia.",
  },

  // OFC (Oceanía)
  {
    id: "kir",
    name: "Kiribati",
    flag: "🇰🇮",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "sam",
    name: "Samoa",
    flag: "🇼🇸",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tga",
    name: "Tonga",
    flag: "🇹🇴",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "fij",
    name: "Fiyi",
    flag: "🇫🇯",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "van",
    name: "Vanuatu",
    flag: "🇻🇺",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "sol",
    name: "Islas Salomón",
    flag: "🇸🇧",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "png",
    name: "Papúa Nueva Guinea",
    flag: "🇵🇬",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "nru",
    name: "Nauru",
    flag: "🇳🇷",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "plw",
    name: "Palau",
    flag: "🇵🇼",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "fsm",
    name: "Micronesia",
    flag: "🇫🇲",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "mhl",
    name: "Islas Marshall",
    flag: "🇲🇭",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tuv",
    name: "Tuvalu",
    flag: "🇹🇻",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "niu",
    name: "Niue",
    flag: "🇳🇺",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "cok",
    name: "Cook Islands",
    flag: "🇨🇰",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "tkl",
    name: "Tokelau",
    flag: "🇹🇰",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "wlf",
    name: "Wallis y Futuna",
    flag: "🇼🇫",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "pyf",
    name: "Polinesia Francesa",
    flag: "🇵🇫",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "ncl",
    name: "Nueva Caledonia",
    flag: "🇳🇨",
    description: "Participante de las clasificatorias de Oceanía.",
  },
  {
    id: "asm",
    name: "Samoa Americana",
    flag: "🇦🇸",
    description: "Participante de las clasificatorias de Oceanía.",
  },

  // CONCACAF (Norteamérica, Centroamérica y el Caribe)
  {
    id: "gum",
    name: "Guam",
    flag: "🇬🇺",
    description: "Participante de las clasificatorias de Oceanía / Asia.",
  },
  {
    id: "vir",
    name: "Islas Vírgenes Estadounidenses",
    flag: "🇻🇮",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "pur",
    name: "Puerto Rico",
    flag: "🇵🇷",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "hai",
    name: "Haití",
    flag: "🇭🇹",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "jam",
    name: "Jamaica",
    flag: "🇯🇲",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "tri",
    name: "Trinidad y Tobago",
    flag: "🇹🇹",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "guy",
    name: "Guyana",
    flag: "🇬🇾",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "sur",
    name: "Surinam",
    flag: "🇸🇷",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bar",
    name: "Barbados",
    flag: "🇧🇧",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "lca",
    name: "Santa Lucía",
    flag: "🇱🇨",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "vin",
    name: "San Vicente y las Granadinas",
    flag: "🇻🇨",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "grn",
    name: "Granada",
    flag: "🇬🇩",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "atg",
    name: "Antigua y Barbuda",
    flag: "🇦🇬",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "kna",
    name: "San Cristóbal y Nieves",
    flag: "🇰🇳",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "dma",
    name: "Dominica",
    flag: "🇩🇲",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "msr",
    name: "Montserrat",
    flag: "🇲🇸",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "aia",
    name: "Anguila",
    flag: "🇦🇮",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bmu",
    name: "Bermudas",
    flag: "🇧🇲",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "cym",
    name: "Islas Caimán",
    flag: "🇰🇾",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "tca",
    name: "Islas Turcas y Caicos",
    flag: "🇹🇨",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "bhs",
    name: "Bahamas",
    flag: "🇧🇸",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "blz",
    name: "Belice",
    flag: "🇧🇿",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "slv",
    name: "El Salvador",
    flag: "🇸🇻",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "gua",
    name: "Guatemala",
    flag: "🇬🇹",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "hon",
    name: "Honduras",
    flag: "🇭🇳",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "nic",
    name: "Nicaragua",
    flag: "🇳🇮",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "crc",
    name: "Costa Rica",
    flag: "🇨🇷",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "pan",
    name: "Panamá",
    flag: "🇵🇦",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "dom",
    name: "República Dominicana",
    flag: "🇩🇴",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
  {
    id: "cub",
    name: "Cuba",
    flag: "🇨🇺",
    description: "Participante de las clasificatorias de CONCACAF.",
  },
];
